import fs from 'node:fs';
const file = process.argv[2] || 'supabase/opportunities.seed.json';
const records = JSON.parse(fs.readFileSync(file, 'utf8'));
const norm = v => String(v ?? '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
const seen = new Set(records.map(r => norm(r.title)));
const make = (title, slug, state, category, subcategory, source, description, education_level='Any', gender_eligibility='All genders') => ({title, slug, organization: state === 'India' ? 'Government of India' : `Government of ${state}`, description, type: category === 'Scholarships' ? 'Scholarship' : 'Government Scheme', category, subcategory, state, district: null, education_level, gender_eligibility, min_age: null, max_age: null, income_limit: null, benefit: 'Support varies by eligibility and current government guidelines', eligibility_text: 'Applicants must meet the current official scheme guidelines and application conditions.', documents_required: ['Identity proof', 'Residence or domicile proof', 'Bank account details', 'Supporting eligibility documents as applicable'], application_start_date: null, application_deadline: null, official_source_url: source, official_application_url: source, status: 'active', verification_status: 'needs_review', _source_note: 'Official scheme family identified; verify current guidelines and application window before publishing.'});
const candidates = [
 make('National Scholarship for Students with Disabilities','national-scholarship-students-with-disabilities','India','Scholarships','Students with disabilities','https://depwd.gov.in/','Educational assistance for eligible students with benchmark disabilities.','School and higher education'),
 make('Maulana Azad National Fellowship','maulana-azad-national-fellowship','India','Scholarships','Minority research fellowship','https://www.minorityaffairs.gov.in/','Research fellowship support for eligible minority students under notified guidelines.','PhD and research'),
 make('UGC Indira Gandhi PG Scholarship for Single Girl Child','ugc-indira-gandhi-pg-scholarship-single-girl-child','India','Scholarships','Single girl child','https://www.ugc.gov.in/','Postgraduate scholarship support for eligible single girl children.','Postgraduate','Women students'),
 make('Tamil Nadu Girl Child Protection Scheme','tamil-nadu-girl-child-protection-scheme','Tamil Nadu','Government Schemes','Girl child welfare','https://www.tn.gov.in/','Support programme for the protection, education and welfare of eligible girl children.','School education','Girls'),
 make('Tamil Nadu Free Laptop Scheme','tamil-nadu-free-laptop-scheme','Tamil Nadu','Education','Digital learning support','https://elcotlaptop.tn.gov.in/','Digital learning device support for eligible students under Tamil Nadu programmes.','Higher education'),
 make('Kerala Vidya Samunnathi Scholarship','kerala-vidya-samunnathi-scholarship','Kerala','Scholarships','Forward community student scholarship','https://kswcfc.kerala.gov.in/','Educational assistance for eligible students from notified economically weaker sections.','School and higher education'),
 make('Kerala Karunya Benevolent Fund','kerala-karunya-benevolent-fund','Kerala','Financial Support','Medical assistance','https://karunya.kerala.gov.in/','Medical financial assistance for eligible patients under Kerala welfare guidelines.'),
 make('Karnataka Minority Scholarship','karnataka-minority-scholarship','Karnataka','Scholarships','Minority student scholarship','https://dom.karnataka.gov.in/','Scholarship support for eligible minority students in Karnataka.','School and higher education'),
 make('Karnataka Arivu Education Loan Scheme','karnataka-arivu-education-loan-scheme','Karnataka','Financial Support','Education finance','https://kmdc.karnataka.gov.in/','Education loan assistance for eligible students from notified communities.','Higher education'),
 make('Telangana Overseas Scholarship for Minorities','telangana-overseas-scholarship-minorities','Telangana','Scholarships','Overseas higher education','https://telangana.gov.in/','Overseas higher-education support for eligible minority students from Telangana.','Postgraduate and doctoral'),
 make('Telangana Chief Minister Overseas Scholarship','telangana-chief-minister-overseas-scholarship','Telangana','Scholarships','Overseas higher education','https://telangana.gov.in/','Overseas study support for eligible students under Telangana scholarship guidelines.','Postgraduate and doctoral'),
 make('Banishree Scholarship','banishree-scholarship','Odisha','Scholarships','Students with disabilities','https://ssepd.odisha.gov.in/','Scholarship support for eligible students with disabilities in Odisha.','School and higher education'),
 make('Sikshashree Scholarship','sikshashree-scholarship','West Bengal','Scholarships','SC students school support','https://oasis.wb.gov.in/','School scholarship support for eligible Scheduled Caste students in West Bengal.','School education'),
 make('Savitribai Phule Kishori Samriddhi Yojana','savitribai-phule-kishori-samriddhi-yojana','Jharkhand','Government Schemes','Adolescent girls','https://jharkhand.gov.in/','Support programme for the education and development of eligible adolescent girls.','School education','Girls'),
 make('Mukhyamantri Balak Balika Protsahan Yojana','mukhyamantri-balak-balika-protsahan-yojana','Bihar','Education','School merit incentive','https://education.bihar.gov.in/','Merit incentive support for eligible students completing notified school examinations.','School education'),
 make('Mukhyamantri Kanya Suraksha Yojana','mukhyamantri-kanya-suraksha-yojana','Bihar','Government Schemes','Girl child welfare','https://icdsonline.bihar.gov.in/','Girl child welfare support under Bihar government guidelines.','School education','Girls'),
 make('Ambedkar DBT Voucher Scheme','ambedkar-dbt-voucher-scheme','Rajasthan','Financial Support','Student accommodation support','https://sje.rajasthan.gov.in/','Direct benefit accommodation support for eligible students from notified communities.','Higher education'),
 make('Mukhyamantri Anuprati Coaching Yojana','mukhyamantri-anuprati-coaching-yojana','Rajasthan','Education','Competitive examination support','https://sje.rajasthan.gov.in/','Coaching support for eligible candidates preparing for professional and competitive examinations.','Higher education'),
 make('Mukhya Mantri Medhavi Vidyarthi Yojana','mukhya-mantri-medhavi-vidyarthi-yojana','Chhattisgarh','Scholarships','Merit higher education','https://schoolscholarship.cg.nic.in/','Merit scholarship support for eligible students in Chhattisgarh.','Higher education'),
 make('Chhattisgarh Post Matric Scholarship','chhattisgarh-post-matric-scholarship','Chhattisgarh','Scholarships','Post-matric scholarship','https://schoolscholarship.cg.nic.in/','Post-matric scholarship support for eligible students in Chhattisgarh.','Post-secondary and higher education'),
 make('Himachal Pradesh Post Matric Scholarship','himachal-pradesh-post-matric-scholarship','Himachal Pradesh','Scholarships','Post-matric scholarship','https://hpepass.cgg.gov.in/','Post-matric scholarship services for eligible students in Himachal Pradesh.','Post-secondary and higher education'),
 make('Uttarakhand Post Matric Scholarship','uttarakhand-post-matric-scholarship','Uttarakhand','Scholarships','Post-matric scholarship','https://escholarship.uk.gov.in/','Post-matric scholarship support for eligible students in Uttarakhand.','Post-secondary and higher education'),
 make('Goa State Higher Education Scholarship','goa-state-higher-education-scholarship','Goa','Scholarships','Higher education support','https://education.goa.gov.in/','Higher-education scholarship support for eligible students in Goa.','Higher education'),
 make('Assam Nijut Moina Scheme','assam-nijut-moina-scheme','Assam','Education','Girls higher education support','https://education.assam.gov.in/','Educational support intended to encourage girls to continue higher education in Assam.','Higher education','Women students'),
 make('Assam Orunodoi Scheme','assam-orunodoi-scheme','Assam','Financial Support','Household support','https://finance.assam.gov.in/','Financial assistance for eligible economically vulnerable households in Assam.'),
 make('Tripura Post Matric Scholarship','tripura-post-matric-scholarship','Tripura','Scholarships','Post-matric scholarship','https://tripura.gov.in/','Post-matric scholarship support for eligible students in Tripura.','Post-secondary and higher education'),
 make('Meghalaya State Merit Scholarship','meghalaya-state-merit-scholarship','Meghalaya','Scholarships','Merit scholarship','https://meghalaya.gov.in/','Merit scholarship support for eligible students in Meghalaya.','Higher education'),
 make('Sikkim State Scholarship','sikkim-state-scholarship','Sikkim','Scholarships','State scholarship','https://sikkim.gov.in/','State scholarship support for eligible students in Sikkim.','School and higher education'),
 make('Arunachal Pradesh State Scholarship','arunachal-pradesh-state-scholarship','Arunachal Pradesh','Scholarships','State scholarship','https://education.arunachal.gov.in/','State scholarship support for eligible students in Arunachal Pradesh.','School and higher education'),
 make('Nagaland State Merit Scholarship','nagaland-state-merit-scholarship','Nagaland','Scholarships','Merit scholarship','https://highereducation.nagaland.gov.in/','Merit scholarship support for eligible students in Nagaland.','Higher education'),
];
for (const item of candidates) { if (records.length >= 200) break; if (!seen.has(norm(item.title))) { records.push(item); seen.add(norm(item.title)); } }
if (records.length !== 200) throw new Error(`Expected 200, got ${records.length}`);
fs.writeFileSync(file, JSON.stringify(records, null, 2) + '\n');
console.log(`Finished at ${records.length} records`);
