import { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock, FileText } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Badge } from '@/components/ui/Badge';
import { getAdminOpportunitySummary } from '@/services/opportunities';

export function Dashboard() {
  const [summary, setSummary] = useState<Awaited<ReturnType<typeof getAdminOpportunitySummary>> | null>(null);
  useEffect(() => { getAdminOpportunitySummary().then(setSummary).catch(() => setSummary({ rows: [], total: 0, active: 0, pending: 0, drafts: 0 })); }, []);
  const metrics = [{ label: 'Total opportunities', value: summary?.total ?? '—', icon: FileText, color: 'bg-gray-100 text-gray-600' }, { label: 'Active opportunities', value: summary?.active ?? '—', icon: CheckCircle2, color: 'bg-success-light text-success' }, { label: 'Needs review', value: summary?.pending ?? '—', icon: Clock, color: 'bg-warning-light text-warning' }, { label: 'Upcoming', value: summary?.drafts ?? '—', icon: AlertTriangle, color: 'bg-accent-light text-accent' }];
  return <div><h1 className="text-3xl font-bold text-primary mb-8">Admin Overview</h1><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-10">{metrics.map(metric => { const Icon = metric.icon; return <div key={metric.label} className="bg-card p-6 rounded-2xl border border-border shadow-sm"><div className="flex items-center gap-4"><div className={`p-3 rounded-xl ${metric.color}`}><Icon className="w-6 h-6" /></div><div><p className="text-sm font-medium text-secondary">{metric.label}</p><p className="text-2xl font-bold text-primary">{metric.value}</p></div></div></div>; })}</div><div className="bg-card rounded-2xl border border-border shadow-sm overflow-hidden"><div className="p-6 border-b border-border flex justify-between items-center"><h2 className="text-lg font-semibold text-primary">Recently Updated</h2><Link to="/admin/opportunities" className="text-sm font-medium text-accent hover:underline">View All</Link></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-background-alt text-secondary"><tr><th className="px-6 py-4 font-medium">Opportunity</th><th className="px-6 py-4 font-medium">Organization</th><th className="px-6 py-4 font-medium">Deadline</th><th className="px-6 py-4 font-medium">Status</th></tr></thead><tbody className="divide-y divide-border">{summary?.rows.map(row => <tr key={row.id}><td className="px-6 py-4 font-medium text-primary">{row.title}</td><td className="px-6 py-4 text-secondary">{row.organization || '—'}</td><td className="px-6 py-4 text-secondary">{row.application_deadline || 'Not set'}</td><td className="px-6 py-4"><Badge variant={row.verification_status === 'verified' ? 'success' : 'warning'}>{row.verification_status}</Badge></td></tr>)}</tbody></table>{!summary?.rows.length && <p className="p-8 text-secondary">No opportunities found. Seed the Supabase database to get started.</p>}</div></div></div>;
}
